# Use an official MySQL image as the base image
FROM mysql:latest

# Set MySQL environment variables (optional)
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=bookstore

# Expose the MySQL port (optional, but usually done for external access)
EXPOSE 3306
